### ISSUE TITLE
Units precipitation.rain different outside forecast in V0.9.2

### ISSUE THREAD

**Issue by juedy62** [inspired-technologies/signalk-openweather-plugin#12]
In Signalk (v2.8.3) Data Browser is the unit indicated different between outside [mm/h] and forecast [mm/s].

Jürgen Debye

**Comment by inspired-technologies** [comment]
Acknowledged - forecast unit should read as mm/h. Will be fixed with next patch release.

**Comment by inspired-technologies** [comment]
Fixed in version 0.9.3
