### ISSUE TITLE
Environment.outside.precipitation.probability is missing. v0.9.2

### ISSUE THREAD

**Issue by juedy62** [inspired-technologies/signalk-openweather-plugin#13]
In Signalk (v2.8.3) Data Browser is the Environment.outside.precipitation.probability is missing. For forecast this value exist.

Jürgen Debye

**Comment by inspired-technologies** [comment]
_environment.outside.*_ values reflect the data provided by [OWM 3.0 OneCall API](https://openweathermap.org/api/one-call-3) response underneith _current_. Precipitation probability is only returned within the _hourly_ forecasts but not for _current_. Hence, this data point cannot be provided.
