### ISSUE TITLE
improper initial value "waiting ..." when plugin start

### ISSUE THREAD

**Issue by cmotelet** [inspired-technologies/signalk-openweather-plugin#2]
The "waiting...." value at plugin launch seem inproper.
https://github.com/inspired-technologies/signalk-openweather-plugin/blob/main/openweather.js#L237
Even if it's nice in the Signal K GUI, it's not very good to change a value from a string type to a numeric or someting else.
http://signalk.org/specification/1.5.0/doc/data_model.html#missing-or-invalid-data
I'm currently stuck in an internal change of the InstrumentPanel code to protect it from some bad values.

**Comment by inspired-technologies** [comment]
Agree that changing data types is not the best option. However, there's also not a good representation of null (as required within the spec) in particular for numeric and datetime data-types - thoughts on how other plugins solve that?

**Comment by tkurki** [comment]
What is the real world case that you are covering here - in what scenarios is the data null?

>there's also not a good representation of null 
What did you mean with this?

Instead of sending text status data in a numeric field why not send nulls in all other fields and put something human oriented in `description`?

A lot noise in the code where you check for null, only to send `noVal ` that is ....null!

**Comment by inspired-technologies** [comment]
> What is the real world case that you are covering here - in what scenarios is the data null?
>
In this plugin it's only the temporary timeframe during startup; after initial response from the API no more null values are provided.

> there's also not a good representation of null
> What did you mean with this?
>
This is in particular for datetime data-types, ie. sunrise, sunset in this case - null does not really seem appropriate.

> Instead of sending text status data in a numeric field why not send nulls in all other fields and put something human oriented in `description`?
>
Agreed - which is more or less the behaviour implemented in the latest patch.

> A lot noise in the code where you check for null, only to send `noVal ` that is ....null!
>
see above - in an earlier iteration value sent on null was different - hence, the checks and pending code cleanup...

**Comment by tkurki** [comment]
>In this plugin it's only the temporary timeframe during startup; after initial response from the API no more null values are provided.

Why send anything until you have data then?

>null does not really seem appropriate.

Null is a special value indicating the absence of a proper value. I don't quite see how the data type plays a role here - a missing time for sunrise is the same as missing value for depth. Sending a string is imho clearly wrong.

**Comment by inspired-technologies** [comment]
> Why send anything until you have data then?
> 
Could be done, but still to be decided what happens after potential API timeout or error, ie. reset to "null" or leave existing vals timing out as per setting in the meta data

> Null is a special value indicating the absence of a proper value. I don't quite see how the data type plays a role here - a missing time for sunrise is the same as missing value for depth. Sending a string is imho clearly wrong.
>
Agreed - probably more a theoretical question whether or not specific data can be nullable. But in this case it does indeed give an appropriate answer to the consumer - in particular compared to the example made of depth not being measurable which  often provides inconsistent feedback.

**Comment by inspired-technologies** [comment]
Closing this as fixed within beta-release 0.5.2. @cmotelet - feel free to re-open in case any other inconsistencies with instruments-panel observed...
