### ISSUE TITLE
Depends on deprecated "signalk-raspberry-pi-temperature" plugin to refresh

### ISSUE THREAD

**Issue by mshulman** [inspired-technologies/signalk-openweather-plugin#4]
This plugin gets a signal to get its forecast from the SignalK-raspberry-pi-temperature plugin, which has been deprecated.

Is there another way to get a one-hour refresh signal than a temperature plugin?

**Comment by inspired-technologies** [comment]
The issue should only be relevant in situations where `navigation.position` isn't updated on a regular basis (ie. fixed station). But will come-up with an alternative in the next pre-release to remove the dependency.

**Comment by inspired-technologies** [comment]
Issue should be resolved; re-moved the dependency in favor of an (hourly fixed) interval, published as [v0.7](https://www.npmjs.com/package/openweather-signalk/v/0.7.0)

**Comment by inspired-technologies** [comment]
Closed - no further comment / action needed.
