### ISSUE TITLE
Full forecast doesn’t download

### ISSUE THREAD

**Issue by SCarns** [inspired-technologies/signalk-openweather-plugin#8]
Simple forecast works fine, but when I switch to full forecast, the plugin sticks in “waiting…” mode.

**Comment by inspired-technologies** [comment]
Seems to work on our dev & prod environments - can you turn on debug logging to see if there's any specific error popping up?

**Comment by SCarns** [comment]
No error. Must be a subscription issue with open weather.

**Comment by SCarns** [comment]
Got.  There was an authentication error in SK. Rework my subscription at OW and generated a new APIkey and its back. Sorry for the intrusion.

**Comment by inspired-technologies** [comment]
Glad you worked it out - thx for the update.
